<?php
namespace App\Traits;
use Illuminate\Http\Response;
trait ApiResponser
{
/**
* Build success response
* @param string|array $data
* @param int $code
* @param string|null $site
* @return Response
*/
public function successResponse($data, $code = Response::HTTP_OK, $site = null)
{
    if ($site) {
        $decoded = json_decode($data, true);
        if (is_array($decoded)) {
            $decoded['site'] = $site;
            $data = json_encode($decoded);
        }
    }
    return response($data, $code)->header('Content-Type', 'application/json');
}

public function validResponse($data, $code = Response::HTTP_OK)
{
return response($data, $code)->header('Content-Type',
'application/json');
}

// error response generated by api gateway itself
public function errorResponse($message, $code)
{
return response()->json(['error' => $message, 'code' => $code],
$code);}

public function errorMessage($message, $code)
{
return response($message, $code)->header('Content-Type',
'application/json');
}
}